# Define a imagem base como php:8-fpm, que é uma imagem oficial do PHP 8 com FastCGI Process Manager (FPM) para lidar com processos PHP.
FROM php:8-fpm

# Executa o comando para instalar a extensão MySQLi na imagem PHP. Isso é necessário para permitir a comunicação com bancos de dados MySQL.
RUN docker-php-ext-install mysqli